#!/bin/bash

#############################################################
#: Title        : Back up                                   #
#: Date         : November 16, 2022                         #
#: Author       : Dennis Phan                               #
#: Version      : 1.0                                       #
#: Description  : Local to remote server back up with rsync #
#: Options      : None                                      #
#############################################################

#import varialbes
# source backup.config
. /opt/backup/backup.config

#using rsync to back up
rsync -aucz -e "ssh -i ~/.ssh/backup_key" ${directory} root@${ip_address}:~/backup
exit 0
